apiVersion: v1
kind: ReplicationController
metadata:
  name: portal
  labels:
    app: portal
    version: "2"
    tier: frontend
spec:
  replicas: 2
  selector:
    app: portal
    version: "2"
  template:
    metadata:
      labels:
        app: portal
        version: "2"
        tier: frontend
    spec:
      containers:
      - name: portal
        image: docker:5000/portal:2
        env:
        - name: GET_HOSTS_FROM
          value: dns
          # value: env
        ports:
        - name: http
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 1
