apiVersion: v1
kind: ReplicationController
metadata:
  name: quotes
  labels:
    app: quotes
    version: "2"
    tier: backend
spec:
  replicas: 2
  selector:
    app: quotes
    version: "2"
  template:
    metadata:
      labels:
        app: quotes
        version: "2"
        tier: backend
    spec:
      containers:
      - name: quotes
        image: docker:5000/quotes:2
        ports:
        - name: http
          containerPort: 9090
        env:
        - name: GET_HOSTS_FROM
          value: dns
          # value: env
        livenessProbe:
          httpGet:
            path: /health
            port: 9090
          initialDelaySeconds: 10
          timeoutSeconds: 1
