apiVersion: v1
kind: Pod
metadata:
  name: quotes
  labels:
    app: quotes
    version: "2"
spec:
  containers:
  - name: quotes
    image: docker:5000/quotes:2
    ports:
    - name: http
      containerPort: 9090
      hostPort: 9090
