apiVersion: v1
kind: Service
metadata:
  name: portal
  labels:
    app: portal
    version: 1
    tier: frontend
spec:
  type: NodePort
  selector:
    app: portal
    version: 1
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 38080
