apiVersion: v1
kind: Service
metadata:
  name: quotes
  labels:
    app: quotes
    version: "2"
    tier: backend
spec:
  type: NodePort
  selector:
    app: quotes
    version: "2"
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 39090
